# Generated by Django 4.0.5 on 2022-11-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='aws_access_token',
            new_name='aws_access_key_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='aws_secret_access_token',
            new_name='aws_secret_access_key',
        ),
    ]
