# Generated by Django 4.0.5 on 2022-11-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(unique=True)),
                ('aws_access_key_id', models.TextField()),
                ('aws_secret_access_key', models.TextField()),
                ('github_access_token', models.TextField()),
                ('jenkins_access_token', models.TextField()),
            ],
        ),
    ]
