# Generated by Django 4.0.5 on 2022-12-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='github_access_token',
        ),
    ]
